cover:
  title: Q's Notebook
  display:
    home: true
    archive: true
    others: true
  features:
    - name: Blog
      icon: "fa fa-blog"
      url: /
    - name: Archive
      icon: "fa fa-box-archive"
      url: /archives/
    - name: Friends
      icon: "fa fa-link"
      url: /friends/
    - name: About
      icon: "fa fa-info"
      url: /about/

navbar:
  visiable: auto # always, auto
  logo: # choose [img] or [icon + title]
    img: 
    icon: "fa fa-q"
    title:
  menu:
    - name: Blog
      icon: "fa fa-blog"
      url: /
    - name: Archive
      icon: "fa fa-box-archive"
      url: /archives/
    - name: Friends
      icon: "fa fa-link"
      url: /friends/
    - name: About
      icon: "fa fa-info"
      url: /about/

sidebar:
  widget_library:
    blogger:
      class: blogger
      display: [desktop] # [desktop, mobile]
      avatar: 
      title: Q
      subtitle: aka Mashio
      jinrishici: false # Poetry Today. You can set a string, and it will be displayed when loading fails.
      social: true
