cover:
  features:
      - name: Blog
        icon: "fa fa-blog"
        url: /
      - name: Archive
        icon: "fa fa-box-archive"
        url: /archives/
      - name: Friends
        icon: "fa fa-link"
        url: /friends/
      - name: About
        icon: "fa fa-info"
        url: /about/
