cover:
  title: Q's Notebook
  display:
    home: true
    archive: true
    others: true
  layout_scheme: dock
  features:
    - name: Blog
      icon: "fa fa-blog"
      url: /
    - name: Archive
      icon: "fa fa-box-archive"
      url: /archives/
    - name: Friends
      icon: "fa fa-link"
      url: /friends/
    - name: About
      icon: "fa fa-info"
      url: /about/

navbar:
  visiable: auto # always, auto
  logo: # choose [img] or [icon + title]
    img: 
    icon: "fa fa-q"
    title:
  menu:
    - name: Blog
      icon: "fa fa-blog"
      url: /
    - name: Archive
      icon: "fa fa-box-archive"
      url: /archives/
    - name: Friends
      icon: "fa fa-link"
      url: /friends/
    - name: About
      icon: "fa fa-info"
      url: /about/

sidebar:
  widget_library:
    blogger:
      class: blogger
      display: [desktop] # [desktop, mobile]
      avatar: 
      title: Q
      subtitle: aka Mashio
      jinrishici: false # Poetry Today. You can set a string, and it will be displayed when loading fails.
      social: true

plugins:
  parallax:
    enable: true
    position: fixed
    shuffle: false
    duration: 10000
    fade: 1500
    images: 
      - volantis-static/media/wallpaper/minimalist/2020/001.webp
      - volantis-static/media/wallpaper/minimalist/2020/002.webp
      - volantis-static/media/wallpaper/minimalist/2020/003.webp
      - volantis-static/media/wallpaper/minimalist/2020/004.webp
      - volantis-static/media/wallpaper/minimalist/2020/005.webp
      - volantis-static/media/wallpaper/minimalist/2020/006.webp
      - volantis-static/media/wallpaper/minimalist/2020/012.webp
      - volantis-static/media/wallpaper/minimalist/2020/016.webp
      - volantis-static/media/wallpaper/minimalist/2020/019.webp
      - volantis-static/media/wallpaper/minimalist/2020/025.webp
      - volantis-static/media/wallpaper/minimalist/2020/033.webp
      - volantis-static/media/wallpaper/minimalist/2020/034.webp
      - volantis-static/media/wallpaper/minimalist/2020/035.webp
      - volantis-static/media/wallpaper/minimalist/2020/038.webp
      - volantis-static/media/wallpaper/minimalist/2020/039.webp
      - volantis-static/media/wallpaper/minimalist/2020/042.webp
      - volantis-static/media/wallpaper/minimalist/2020/046.webp
      - volantis-static/media/wallpaper/minimalist/2020/051.webp
      - volantis-static/media/wallpaper/minimalist/2020/052.webp
      - volantis-static/media/wallpaper/minimalist/2020/054.webp
      - volantis-static/media/wallpaper/minimalist/2020/056.webp
